<?php

use App\Models\Blog;
use App\Models\Job;
use App\Services\StructuredDataService;
use Database\Seeders\AiContentWriterUsaBlogSeeder;
use Database\Seeders\GraphicDesignerJobsUsaBlogSeeder;

use function Pest\Laravel\get;

const DESIGN_SLUG = 'graphic-designer-jobs-in-usa';

const DESIGN_APPLY_URL = 'https://www.indeed.com/q-graphic-designer-jobs.html';

beforeEach(function () {
    $this->seed(GraphicDesignerJobsUsaBlogSeeder::class);
});

it('publishes the guide with its SEO fields inside the snippet limits', function () {
    $blog = Blog::where('slug', DESIGN_SLUG)->first();

    expect($blog)->not->toBeNull()
        ->and($blog->status)->toBe('published')
        ->and($blog->featured_image)->toBe('blogs/graphic-designer-jobs-in-usa.jpg')
        ->and($blog->excerpt)->not->toBeEmpty()
        // blogs.excerpt is a varchar(255); sqlite accepts more, MySQL does not.
        ->and(mb_strlen($blog->excerpt))->toBeLessThanOrEqual(255)
        ->and($blog->reading_time)->toBeGreaterThan(3)
        ->and(mb_strlen($blog->meta_title))->toBeLessThanOrEqual(60)
        ->and(mb_strlen($blog->meta_description))->toBeLessThanOrEqual(160);
});

it('ships every image it references', function () {
    $blog = Blog::where('slug', DESIGN_SLUG)->first();

    preg_match_all('#/public/storage/(blogs/[\w.-]+\.jpg)#', $blog->content, $matches);

    expect($matches[1])->toHaveCount(2);

    foreach (array_merge([$blog->featured_image], $matches[1]) as $path) {
        expect(file_exists(storage_path('app/public/'.$path)))->toBeTrue("missing image: {$path}");
    }
});

it('anchors pay on the BLS median rather than aggregator ranges', function () {
    $body = Blog::where('slug', DESIGN_SLUG)->value('content');

    expect($body)->toContain('$62,960')
        ->toContain('$39,520')
        ->toContain('$104,910');
});

it('replaces the growing-demand framing with the published projection', function () {
    // The draft opened and closed on demand climbing. BLS projects a decline,
    // and the 16,000 annual openings are replacement rather than growth.
    $body = Blog::where('slug', DESIGN_SLUG)->value('content');

    expect($body)->toContain('decline 2 per cent between 2025 and 2035')
        ->toContain('16,000 openings a year')
        ->toContain('come from replacement, not growth')
        ->and($body)->not->toContain('demand for visual design skills keeps climbing');
});

it('points at the adjacent occupation the projection actually favours', function () {
    $response = get('/blog/'.DESIGN_SLUG)->assertOk();

    $response->assertSee('web developers and digital designers', false)
        ->assertSee('grow 5 per cent from 2025 to 2035', false)
        ->assertSee('$92,650');
});

it('prices a freelance rate against tax, software and platform fees', function () {
    // The draft compared hourly freelance rates to salaries with no adjustment.
    $body = Blog::where('slug', DESIGN_SLUG)->value('content');

    expect($body)->toContain('15.3%')
        ->toContain('Schedule C')
        ->toContain('1099-NEC')
        ->toContain('$54.99 a month')
        ->toContain('Fiverr takes a flat 20%')
        ->toContain('has not been a flat 10% since 1 May 2025');
});

it('carries the copyright position on AI-generated client work', function () {
    $body = Blog::where('slug', DESIGN_SLUG)->value('content');

    expect($body)->toContain('human authorship is required for copyright protection')
        ->toContain('wholly generated by AI is not copyrightable')
        ->toContain('de minimis');
});

it('carries FAQ markup built from the post body', function () {
    $faqs = app(StructuredDataService::class)
        ->faqsFromHtml(Blog::where('slug', DESIGN_SLUG)->value('content'));

    // "People Also Search For" uses the same h3/p shape and must stay out.
    expect($faqs)->toHaveCount(8)
        ->and(array_column($faqs, 'question'))
        ->not->toContain('Graphic design jobs near me');

    get('/blog/'.DESIGN_SLUG)->assertSee('"FAQPage"', false);
});

it('drops JobPosting markup because the apply link is a search page', function () {
    // The draft's link carried a ?vjk= search-preview parameter; it is stripped.
    expect(app(StructuredDataService::class)->describesSingleVacancy(DESIGN_APPLY_URL))->toBeFalse();

    expect(get('/blog/'.DESIGN_SLUG)->getContent())->not->toContain('"JobPosting"');
});

it('creates one US listing and does not duplicate it on a re-run', function () {
    $this->seed(GraphicDesignerJobsUsaBlogSeeder::class);

    $jobs = Job::where('application_url', DESIGN_APPLY_URL)->get();

    expect($jobs)->toHaveCount(1)
        ->and(Blog::where('slug', DESIGN_SLUG)->count())->toBe(1)
        ->and($jobs->first()->location->country)->toBe('United States')
        ->and($jobs->first()->salary_minimum)->toBeNull()
        ->and($jobs->first()->description)->toContain('median of $62,960');
});

it('links to and from the AI content writer guide', function () {
    $this->seed(AiContentWriterUsaBlogSeeder::class);

    get('/blog/'.DESIGN_SLUG)->assertOk()
        ->assertSee('/blog/ai-content-writer-jobs-in-usa', false)
        ->assertSee('/blog/ats-resume-writer-jobs-in-usa', false)
        ->assertSee('/blog/remote-customer-service-jobs', false);

    get('/blog/ai-content-writer-jobs-in-usa')->assertOk()
        ->assertSee('/blog/'.DESIGN_SLUG, false);
});
